server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: book-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/books/**
              filters:
                - AddRequestHeader=X-Request-Foo, Bar
                - AddResponseHeader=X-Response-Foo, Bar